"""Машиночитаемый реестр правил, извлечённых из русского стайл-гайда."""

from __future__ import annotations

from typing import Any

STYLE_GUIDE_SOURCE = "РУ Style Guide.docx"

RULES: list[dict[str, Any]] = [
    {
        "id": "RuStyleGuide.Glossary",
        "section": "Ключевые рекомендации / Глоссарий",
        "group": "Ключевые рекомендации",
        "name": "Глоссарий",
        "rule": "Использовать утвержденные термины из глоссария.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Словарные замены применяются как термины и словосочетания, а не как разовые примеры.",
        "good_examples": ["Укажите электронную почту.", "Фильтрация трафика включена.", "Веб-сервер работает."],
        "bad_examples": ["Укажите email.", "Очистка трафика включена.", "web-сервер работает."],
    },
    {
        "id": "RuStyleGuide.ProductNames",
        "section": "Ключевые рекомендации / Наименование продукта, компонентов, юр.лиц, компании",
        "group": "Ключевые рекомендации",
        "name": "Наименования продуктов и компании",
        "rule": "Использовать полные утвержденные названия продукта и компании.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются сокращения и неутвержденные варианты названий.",
        "good_examples": ["Kaspersky DDoS Protection защищает инфраструктуру.", "DDoS-атаки"],
        "bad_examples": ["KDP защищает инфраструктуру.", "Kaspersky DDOS Protection", "KasperskyDDoS Protection"],
    },
    {
        "id": "RuStyleGuide.UITerms_SettingsGroup",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Блок параметров",
        "group": "Ключевые рекомендации",
        "name": "Блок параметров",
        "rule": "Для settings group использовать «блок параметров», а не «группа параметров».",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется термин элемента интерфейса в разных контекстах.",
        "good_examples": ["В блоке параметров выберите значение."],
        "bad_examples": ["В группе параметров выберите значение."],
    },
    {
        "id": "RuStyleGuide.UITerms_Tab",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Вкладка",
        "group": "Ключевые рекомендации",
        "name": "Вкладка",
        "rule": "Вкладку выбирают, а не активизируют, открывают или переходят на нее.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются запрещенные глаголы рядом с термином «вкладка».",
        "good_examples": ["Выберите вкладку Общие."],
        "bad_examples": ["Откройте вкладку Общие."],
    },
    {
        "id": "RuStyleGuide.UITerms_Click",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Кнопка",
        "group": "Ключевые рекомендации",
        "name": "Клик",
        "rule": "Не использовать «кликнуть» и формы этого слова.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются словоформы «кликнуть», если они описывают действие пользователя.",
        "good_examples": ["Нажмите кнопку «Выйти»."],
        "bad_examples": ["Кликните на кнопку «Выйти»."],
    },
    {
        "id": "RuStyleGuide.UITerms_QuotedLabels",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Кнопка",
        "group": "Ключевые рекомендации",
        "name": "Кавычки в названиях кнопок",
        "rule": "Названия кнопок в тексте заключать в русские кавычки «елочки».",
        "engine": "manual",
        "automation": "partial",
        "severity": "warning",
        "generalization": (
            "Правило применяется к имени элемента после слова «кнопка», "
            "но не к общему описанию кнопки без собственного названия."
        ),
        "good_examples": ["Кнопка «Добавить» открывает окно создания правила."],
        "bad_examples": ["Кнопка Добавить открывает окно создания правила."],
        "relationships": {"specializes": ["Базовая.Форматирование"]},
        "conflict_family": "ui-button-label-format",
    },
    {
        "id": "RuStyleGuide.CrossRef_Link",
        "section": "Форматирование / Перекрестные ссылки",
        "group": "Форматирование",
        "name": "Ссылка на раздел документации",
        "rule": "Отсылку к конкретному разделу документации оформлять гиперссылкой.",
        "engine": "manual",
        "automation": "partial",
        "severity": "warning",
        "generalization": (
            "Проверяется наличие ссылки у названия раздела в конструкциях "
            "«см. в разделе», «подробнее в разделе» и аналогичных отсылках."
        ),
        "good_examples": ["Подробнее см. в разделе «Настройка фильтрации» (гиперссылка)."],
        "bad_examples": ["Подробнее см. в разделе Настройка фильтрации."],
        "relationships": {"specializes": ["Базовая.Форматирование"]},
        "conflict_family": "cross-reference-format",
    },
    {
        "id": "RuStyleGuide.UITerms_DoubleClick",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Кнопка",
        "group": "Ключевые рекомендации",
        "name": "Двойной щелчок",
        "rule": "Использовать «двойным щелчком мыши», а не «дважды кликните».",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется устойчивый неверный способ описания двойного нажатия.",
        "good_examples": ["Запустите файл двойным щелчком мыши."],
        "bad_examples": ["Дважды кликните по файлу."],
    },
    {
        "id": "RuStyleGuide.UITerms_RightClick",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Кнопка",
        "group": "Ключевые рекомендации",
        "name": "Правая кнопка мыши",
        "rule": "Описывать действие как нажатие на правую кнопку мыши.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется нежелательная конструкция «щелкните правой кнопкой мыши».",
        "good_examples": ["Откройте меню нажатием на правую кнопку мыши."],
        "bad_examples": ["Щелкните правой кнопкой мыши по задаче."],
    },
    {
        "id": "RuStyleGuide.UITerms_Menu",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Меню",
        "group": "Ключевые рекомендации",
        "name": "Контекстное меню",
        "rule": "Использовать «контекстное меню», а не «динамическое» или «всплывающее».",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются запрещенные варианты названия элемента меню.",
        "good_examples": ["Откройте контекстное меню объекта."],
        "bad_examples": ["Откройте всплывающее меню объекта."],
    },
    {
        "id": "RuStyleGuide.UITerms_WindowResize",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Окно",
        "group": "Ключевые рекомендации",
        "name": "Размеры окна",
        "rule": "Использовать «задать размеры окна».",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются нежелательные глаголы изменения размера окна.",
        "good_examples": ["Задайте размеры окна."],
        "bad_examples": ["Раздвиньте окно."],
    },
    {
        "id": "RuStyleGuide.UITerms_WindowMove",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Окно",
        "group": "Ключевые рекомендации",
        "name": "Перемещение окна",
        "rule": "Использовать «переместить окно».",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются нежелательные глаголы для действия с окном.",
        "good_examples": ["Переместите окно."],
        "bad_examples": ["Перетащите окно."],
    },
    {
        "id": "RuStyleGuide.UITerms_Field",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Поле",
        "group": "Ключевые рекомендации",
        "name": "Значение в поле",
        "rule": "Значение в поле можно указать или ввести, не определить.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется глагол рядом со словом «значение» в UI-контексте.",
        "good_examples": ["Укажите значение в поле."],
        "bad_examples": ["Определите значение в поле."],
    },
    {
        "id": "RuStyleGuide.UITerms_Slider",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Ползунок",
        "group": "Ключевые рекомендации",
        "name": "Ползунок",
        "rule": "Использовать «ползунок», а не «бегунок».",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется термин элемента интерфейса.",
        "good_examples": ["Переместите ползунок."],
        "bad_examples": ["Переместите бегунок."],
    },
    {
        "id": "RuStyleGuide.UITerms_List",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Список",
        "group": "Ключевые рекомендации",
        "name": "Элементы списка",
        "rule": "Список содержит элементы, не позиции, строки или пункты.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "warning",
        "generalization": "Проверяется терминология рядом со словом «список».",
        "good_examples": ["Выберите элемент списка."],
        "bad_examples": ["Выберите пункт списка."],
    },
    {
        "id": "RuStyleGuide.UITerms_Checkbox",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Флажок",
        "group": "Ключевые рекомендации",
        "name": "Флажок",
        "rule": "Использовать «флажок», а не «чекбокс».",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется термин элемента интерфейса и его распространенные варианты.",
        "good_examples": ["Установите флажок."],
        "bad_examples": ["Установите чекбокс."],
    },
    {
        "id": "RuStyleGuide.UITerms_CheckboxVerbs",
        "section": "Ключевые рекомендации / Названия элементов интерфейса / Флажок",
        "group": "Ключевые рекомендации",
        "name": "Глаголы с флажком",
        "rule": "Флажок можно установить или снять.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются запрещенные глаголы рядом с термином «флажок».",
        "good_examples": ["Снимите флажок."],
        "bad_examples": ["Отключите флажок."],
    },
    {
        "id": "RuStyleGuide.Units_International",
        "section": "Ключевые рекомендации / Единицы измерения",
        "group": "Ключевые рекомендации",
        "name": "Единицы измерения",
        "rule": "В русскоязычных текстах использовать русские обозначения единиц измерения.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются международные обозначения там, где у гайда есть русский вариант.",
        "good_examples": ["Скорость составляет 10 Мбит/с."],
        "bad_examples": ["Скорость составляет 10 Mbit/s."],
    },
    {
        "id": "RuStyleGuide.Units_Period",
        "section": "Ключевые рекомендации / Единицы измерения",
        "group": "Ключевые рекомендации",
        "name": "Точка после единиц",
        "rule": "Не ставить точку после сокращения единицы измерения.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются сокращения единиц с точкой.",
        "good_examples": ["Время ожидания 5 мин."],
        "bad_examples": ["Значение равно 5 мин.."],
    },
    {
        "id": "RuStyleGuide.FileFormats_FormatCase",
        "section": "Ключевые рекомендации / Расширение и формат файлов",
        "group": "Ключевые рекомендации",
        "name": "Форматы файлов",
        "rule": "Форматы файлов пишутся прописными буквами.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются известные форматы из таблицы гайда.",
        "good_examples": ["Файл формата JSON."],
        "bad_examples": ["Файл формата json."],
    },
    {
        "id": "RuStyleGuide.FileFormats_ExtensionCase",
        "section": "Ключевые рекомендации / Расширение и формат файлов",
        "group": "Ключевые рекомендации",
        "name": "Расширения файлов",
        "rule": "Расширения файлов пишутся строчными буквами с точкой.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются известные расширения из таблицы гайда.",
        "good_examples": ["Файл с расширением .txt."],
        "bad_examples": ["Файл с расширением .TXT."],
    },
    {
        "id": "RuStyleGuide.Bureaucracy",
        "section": "Общие принципы / Канцеляризмы",
        "group": "Общие принципы",
        "name": "Канцеляризмы",
        "rule": "Использовать простой язык вместо канцеляризмов.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "warning",
        "generalization": "Проверяется словарь устойчивых канцелярских выражений.",
        "good_examples": ["Настройте приложение."],
        "bad_examples": ["Пройдите процедуру настройки приложения."],
    },
    {
        "id": "RuStyleGuide.Jargon",
        "section": "Общие принципы / Терминология",
        "group": "Общие принципы",
        "name": "Жаргонизмы",
        "rule": "Не использовать профессиональный жаргон вместо терминов.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется словарь жаргонных терминов и утвержденных замен.",
        "good_examples": ["Системный администратор настроил сервер."],
        "bad_examples": ["Сисадмин настроил сервер."],
    },
    {
        "id": "RuStyleGuide.Anglicisms",
        "section": "Общие принципы / Англицизмы",
        "group": "Общие принципы",
        "name": "Англицизмы",
        "rule": "Заменять англицизмы освоенными русскими синонимами, если это не мешает пониманию.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "warning",
        "generalization": "Проверяется словарь нежелательных англицизмов, IT-термины не считаются ошибкой сами по себе.",
        "good_examples": ["Установка завершена."],
        "bad_examples": ["Инсталляция завершена."],
    },
    {
        "id": "RuStyleGuide.SentenceLength",
        "section": "Общие принципы / Длинные предложения",
        "group": "Общие принципы",
        "name": "Длинные предложения",
        "rule": "Стараться писать не больше 25 слов в предложении.",
        "engine": "python",
        "automation": "partial",
        "severity": "warning",
        "generalization": "Считаются слова в предложении; результат — предупреждение, потому что правило зависит от контекста.",
        "good_examples": ["Откройте раздел. Выберите нужный элемент."],
        "bad_examples": ["Откройте раздел, выберите нужный элемент, настройте параметры, сохраните изменения, проверьте результат выполнения операции в личном кабинете, добавьте комментарий, приложите файл и отправьте подробный отчет администратору проекта."],
    },
    {
        "id": "RuStyleGuide.HomogeneousMembers",
        "section": "Общие принципы / Однородные члены предложения",
        "group": "Общие принципы",
        "name": "Однородные члены",
        "rule": "Не использовать больше трех однородных членов подряд.",
        "engine": "vale",
        "automation": "partial",
        "severity": "warning",
        "generalization": "Проверяется типичный список однородных членов; сложный синтаксис требует ручной оценки.",
        "good_examples": ["Система проверяет и сохраняет данные."],
        "bad_examples": ["Система проверяет, сохраняет, отправляет и архивирует данные."],
    },
    {
        "id": "RuStyleGuide.TimelessDocs",
        "section": "Общие принципы / Бессрочная документация",
        "group": "Общие принципы",
        "name": "Бессрочная документация",
        "rule": "Избегать временных указаний.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "warning",
        "generalization": "Проверяется словарь временных маркеров, которые делают документацию недолговечной.",
        "good_examples": ["В версии продукта доступна функция."],
        "bad_examples": ["В последней версии продукта доступна функция."],
    },
    {
        "id": "RuStyleGuide.Consistency",
        "section": "Общие принципы / Однозначность",
        "group": "Общие принципы",
        "name": "Одно понятие — одно слово",
        "rule": "Использовать одно наименование для одного понятия по всему тексту.",
        "engine": "vale",
        "automation": "partial",
        "severity": "error",
        "generalization": "Проверяются пары известных терминов; остальные случаи требуют ручной оценки.",
        "good_examples": ["Трафик направляется в Центр очистки. Центр очистки фильтрует трафик."],
        "bad_examples": ["Трафик направляется в Центр очистки. Кластер фильтрующих узлов фильтрует трафик."],
    },
    {
        "id": "RuStyleGuide.InclusiveLanguage",
        "section": "Общие принципы / Гендерно-нейтральный язык",
        "group": "Общие принципы",
        "name": "Инклюзивный язык",
        "rule": "Избегать сленга, оскорбительных и политически окрашенных терминов.",
        "engine": "vale",
        "automation": "partial",
        "severity": "warning",
        "generalization": "Проверяется словарь явно нежелательных слов; пограничные случаи требуют ручной оценки.",
        "good_examples": ["Используйте нейтральную терминологию."],
        "bad_examples": ["Добавьте запись в белый список."],
    },
    {
        "id": "RuStyleGuide.FormalYou",
        "section": "Общие принципы / Обращение к пользователю",
        "group": "Общие принципы",
        "name": "Вы и ваш",
        "rule": "Обращаться к пользователю на «вы» со строчной буквы; избегать лишних обращений.",
        "engine": "python",
        "automation": "partial",
        "severity": "error",
        "generalization": "Проверяется написание с прописной буквы; уместность обращений оценивается частично.",
        "good_examples": ["Проверьте ваши записи."],
        "bad_examples": ["Проверьте Ваши записи."],
    },
    {
        "id": "RuStyleGuide.Possessives",
        "section": "Общие принципы / Обращение к пользователю",
        "group": "Общие принципы",
        "name": "Лишние вы/ваш/наш",
        "rule": "Избегать лишних обращений и притяжательных местоимений, если личное не противопоставляется общему.",
        "engine": "manual",
        "automation": "manual",
        "severity": "warning",
        "generalization": "Правило зависит от смысла: «ваши записи» допустимо, «наш сайт» нежелательно. Автоматическая проверка отключена.",
        "good_examples": ["Записи доступны в личном кабинете."],
        "bad_examples": ["Добро пожаловать на наш сайт."],
    },
    {
        "id": "RuStyleGuide.Please",
        "section": "Общие принципы / Пожалуйста",
        "group": "Общие принципы",
        "name": "Пожалуйста",
        "rule": "Использовать «пожалуйста» только при неудобстве для пользователя или ошибке программы.",
        "engine": "vale",
        "automation": "partial",
        "severity": "warning",
        "generalization": "Фиксируется наличие слова; допустимость зависит от контекста.",
        "good_examples": ["Пожалуйста, подождите."],
        "bad_examples": ["Пожалуйста, проверьте состояние лицензии."],
    },
    {
        "id": "RuStyleGuide.Abbreviations",
        "section": "Язык, грамматика / Аббревиатуры",
        "group": "Язык, грамматика",
        "name": "Аббревиатуры",
        "rule": "Необщепринятую аббревиатуру нужно расшифровать при первом использовании.",
        "engine": "vale",
        "automation": "partial",
        "severity": "suggestion",
        "generalization": "Проверяются подозрительные аббревиатуры, но корректность первого упоминания зависит от всего документа.",
        "good_examples": ["Локальный Центр очистки (ЛЦО) фильтрует трафик."],
        "bad_examples": ["ЛЦО фильтрует трафик."],
    },
    {
        "id": "RuStyleGuide.PassiveVoice",
        "section": "Язык, грамматика / Активный залог",
        "group": "Язык, грамматика",
        "name": "Активный залог",
        "rule": "Использовать активный залог вместо пассивного.",
        "engine": "manual",
        "automation": "manual",
        "severity": "warning",
        "generalization": "Пассив зависит от синтаксиса и смысла. Старое автоматическое правило было шумным, поэтому правило оставлено как ручное.",
        "good_examples": ["Мы отправили вам SMS с кодом авторизации."],
        "bad_examples": ["Код для авторизации был отправлен в SMS."],
    },
    {
        "id": "RuStyleGuide.Anthropomorphism",
        "section": "Язык, грамматика / Антропоморфизм",
        "group": "Язык, грамматика",
        "name": "Антропоморфизм",
        "rule": "Не приписывать человеческие качества программному обеспечению или оборудованию.",
        "engine": "python",
        "automation": "partial",
        "severity": "warning",
        "generalization": "Проверяются технические субъекты и глаголы человеческого восприятия; результат требует проверки контекста.",
        "good_examples": ["Компьютер обнаружил новое устройство."],
        "bad_examples": ["Компьютер увидел новое устройство."],
    },
    {
        "id": "RuStyleGuide.LetterYo",
        "section": "Язык, грамматика / Буква «ё»",
        "group": "Язык, грамматика",
        "name": "Буква ё",
        "rule": "Не использовать букву «ё», кроме случаев двусмысленности.",
        "engine": "vale",
        "automation": "partial",
        "severity": "warning",
        "generalization": "Проверяется буква «ё»; исключения требуют словаря неоднозначных слов.",
        "good_examples": ["Все под контролем."],
        "bad_examples": ["Всё под контролем."],
        "constraints": {"forbidden_introduced_chars": ["ё", "Ё"]},
        "relationships": {"supersedes": ["Базовая.Орфография"]},
        "conflict_family": "letter-yo-policy",
    },
    {
        "id": "RuStyleGuide.Imperative",
        "section": "Язык, грамматика / Повелительное наклонение",
        "group": "Язык, грамматика",
        "name": "Повелительное наклонение",
        "rule": "Использовать повелительное наклонение вместо модальных конструкций.",
        "engine": "vale",
        "automation": "partial",
        "severity": "warning",
        "generalization": "Проверяются типовые модальные конструкции; полная грамматическая оценка требует ручной проверки.",
        "good_examples": ["Нажмите кнопку."],
        "bad_examples": ["Вам следует нажать кнопку."],
    },
    {
        "id": "RuStyleGuide.Quotes_Straight",
        "section": "Пунктуация / Кавычки",
        "group": "Пунктуация",
        "name": "Кавычки-елочки",
        "rule": "Использовать русские кавычки «елочки» вместо прямых кавычек.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются прямые кавычки в русском тексте.",
        "good_examples": ["Нажмите «Да»."],
        "bad_examples": ["Нажмите \"Да\"."],
    },
    {
        "id": "RuStyleGuide.Quotes_LatinInQuotes",
        "section": "Пунктуация / Кавычки",
        "group": "Пунктуация",
        "name": "Латиница без кавычек",
        "rule": "Иностранные названия на латинице пишутся без кавычек.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются латинские слова внутри кавычек.",
        "good_examples": ["Kaspersky защищает инфраструктуру."],
        "bad_examples": ["«Kaspersky» защищает инфраструктуру."],
    },
    {
        "id": "RuStyleGuide.Parentheses",
        "section": "Пунктуация / Скобки",
        "group": "Пунктуация",
        "name": "Скобки",
        "rule": "Важный текст выносить из скобок; неважный убирать. Исключение — расшифровки аббревиатур.",
        "engine": "vale",
        "automation": "partial",
        "severity": "suggestion",
        "generalization": "Фиксируются скобки как повод для проверки; важность текста оценивает автор.",
        "good_examples": ["Локальный Центр очистки (ЛЦО) фильтрует трафик."],
        "bad_examples": ["Настройте параметр (если он доступен)."],
    },
    {
        "id": "RuStyleGuide.Dash_EmDash",
        "section": "Пунктуация / Тире и дефис",
        "group": "Пунктуация",
        "name": "Длинное тире",
        "rule": "Использовать среднее тире (–), а не длинное (—).",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется сам символ тире, а не слова вокруг него.",
        "good_examples": ["Система – это решение."],
        "bad_examples": ["Система — это решение."],
        "constraints": {"forbidden_chars": ["—"], "required_chars": ["–"]},
        "relationships": {"supersedes": ["Базовая.Пунктуация"]},
        "conflict_family": "dash-symbol-policy",
    },
    {
        "id": "RuStyleGuide.Dash_NoSpace",
        "section": "Пунктуация / Тире и дефис",
        "group": "Пунктуация",
        "name": "Пробелы вокруг тире",
        "rule": "До и после тире ставить пробелы.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется среднее тире без пробела рядом с буквами.",
        "good_examples": ["Система – это решение."],
        "bad_examples": ["Система–это решение."],
    },
    {
        "id": "RuStyleGuide.Dash_HyphenSpace",
        "section": "Пунктуация / Тире и дефис",
        "group": "Пунктуация",
        "name": "Пробелы вокруг дефиса",
        "rule": "До и после дефиса пробел не ставить.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "warning",
        "generalization": "Проверяется дефис между словами с пробелами вокруг.",
        "good_examples": ["Прокси-сервер доступен."],
        "bad_examples": ["Прокси - сервер доступен."],
    },
    {
        "id": "RuStyleGuide.Slash_Words",
        "section": "Пунктуация / Косая черта (слэш/, бэкслэш\\)",
        "group": "Пунктуация",
        "name": "Слэш между словами",
        "rule": "Не использовать слэш между словами в обычном тексте.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "warning",
        "generalization": "Проверяется слэш между словами и протокольными сокращениями; URL, файловые пути и единицы измерения не относятся к этому правилу.",
        "good_examples": ["Клиента или партнера.", "https://example.com/folder/page.html", "10 Мбит/с"],
        "bad_examples": ["Клиента/партнера.", "TCP/UDP сервисы."],
    },
    {
        "id": "RuStyleGuide.Terminology_WebPrefix",
        "section": "Язык, грамматика / Термины на латинице",
        "group": "Язык, грамматика",
        "name": "Русское написание «веб-»",
        "rule": "В русскоязычном тексте писать «веб-», а не латинское «web-».",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется латинский префикс web- перед русским словом: web-сервер, web-сервис, web-ресурс.",
        "good_examples": ["Веб-сервер работает."],
        "bad_examples": ["web-сервер работает."],
    },
    {
        "id": "RuStyleGuide.Spacing_Double",
        "section": "Пунктуация / Пробелы",
        "group": "Пунктуация",
        "name": "Двойные пробелы",
        "rule": "Не использовать лишние пробелы внутри текста.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются два и более пробела между непробельными символами.",
        "good_examples": ["Проконсультируйтесь с экспертом."],
        "bad_examples": ["Проконсультируйтесь  с экспертом."],
    },
    {
        "id": "RuStyleGuide.Currency_FromAmount",
        "section": "Форматирование / Числа и цены",
        "group": "Форматирование",
        "name": "Пробел после «от»",
        "rule": "Ставить пробел между предлогом «от» и суммой.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется слитное написание «от» с числом.",
        "good_examples": ["Ежемесячно от 15 000 ₽."],
        "bad_examples": ["Ежемесячно от15 000 ₽."],
    },
    {
        "id": "RuStyleGuide.Grammar_BezGerund",
        "section": "Язык, грамматика / Часто встречающиеся языковые ошибки",
        "group": "Язык, грамматика",
        "name": "Без + существительное",
        "rule": "После «без» использовать существительное, а не деепричастие.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется конструкция «без + деепричастие» вроде «без нарушая».",
        "good_examples": ["Без нарушения принципов шифрования."],
        "bad_examples": ["Без нарушая принципы шифрования."],
    },
    {
        "id": "RuStyleGuide.Agreement",
        "section": "Язык, грамматика / Согласование слов",
        "group": "Язык, грамматика",
        "name": "Согласование прилагательного и существительного",
        "rule": "Прилагательное должно согласовываться с существительным в падеже, числе и роде.",
        "engine": "python",
        "automation": "partial",
        "severity": "warning",
        "generalization": "Морфологически проверяются соседние пары «прилагательное + существительное»; результат требует ручной оценки при неоднозначном разборе.",
        "good_examples": ["Асимметричная фильтрация."],
        "bad_examples": ["Асимметричная фильтрации."],
    },
    {
        "id": "RuStyleGuide.SubjectVerbAgreement",
        "section": "Язык, грамматика / Согласование слов",
        "group": "Язык, грамматика",
        "name": "Согласование подлежащего и сказуемого",
        "rule": "Подлежащее и сказуемое должны согласовываться в числе.",
        "engine": "python",
        "automation": "partial",
        "severity": "warning",
        "generalization": "Проверяются близкие конструкции с подлежащим во множественном числе и сказуемым в единственном числе.",
        "good_examples": ["Все компоненты защиты находятся в облаке."],
        "bad_examples": ["Все компоненты защиты находится в облаке."],
    },
    {
        "id": "RuStyleGuide.Formatting_LineSeparator",
        "section": "Форматирование / Служебные символы",
        "group": "Форматирование",
        "name": "Служебный перенос строки",
        "rule": "Не оставлять в видимом тексте служебные символы переноса строки.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяется символ U+2028, который часто попадает в текст из CMS и ломает нормальную типографику.",
        "good_examples": ["Балансировка трафика осуществляется на двух этапах."],
        "bad_examples": ["Балансировка трафика осуществляется на двух этапах:\u2028до фильтрации."],
    },
    {
        "id": "RuStyleGuide.Formatting_SoftHyphen",
        "section": "Форматирование / Служебные символы",
        "group": "Форматирование",
        "name": "Мягкий перенос",
        "rule": "Не оставлять мягкий перенос внутри видимого слова.",
        "engine": "vale",
        "automation": "manual",
        "severity": "error",
        "generalization": "Автоматическая проверка отключена: U+00AD часто используется версткой для адаптивных переносов и должен удаляться на этапе извлечения текста.",
        "good_examples": ["Многопользовательское управление."],
        "bad_examples": ["Многопользова\u00adтельское управление."],
    },
    {
        "id": "RuStyleGuide.Content_PlaceholderText",
        "section": "Форматирование / Служебные заглушки",
        "group": "Форматирование",
        "name": "CMS-заглушка",
        "rule": "Не оставлять служебные заглушки в опубликованном тексте.",
        "engine": "vale",
        "automation": "manual",
        "severity": "error",
        "generalization": "Автоматическая проверка отключена: на сайте это может быть служебный/скрытый текст CMS, а не видимый контент.",
        "good_examples": ["Новости"],
        "bad_examples": ["текст"],
    },
    {
        "id": "RuStyleGuide.Apostrophe_CyrillicEnding",
        "section": "Язык, грамматика / Термины на латинице",
        "group": "Язык, грамматика",
        "name": "Апостроф перед русским окончанием",
        "rule": "Не присоединять русское окончание к латинскому термину через апостроф.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "warning",
        "generalization": "Проверяются конструкции вида «DDoS’еров», но не английские названия вроде Let’s Encrypt.",
        "good_examples": ["DDoS-атаки", "Let’s Encrypt"],
        "bad_examples": ["DDoS’еров"],
    },
    {
        "id": "RuStyleGuide.IPAddress",
        "section": "Ключевые рекомендации / Скрытие реальной персональной информации",
        "group": "Ключевые рекомендации",
        "name": "IP-адрес",
        "rule": "IP-адрес писать с заглавными IP и через дефис.",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются неверные варианты написания термина.",
        "good_examples": ["Укажите IP-адрес."],
        "bad_examples": ["Укажите ip-адрес."],
    },
    {
        "id": "RuStyleGuide.DearUser",
        "section": "Общие принципы / Обращение к пользователю",
        "group": "Общие принципы",
        "name": "Уважаемый пользователь",
        "rule": "Не использовать официально-деловое обращение «Уважаемый пользователь».",
        "engine": "vale",
        "automation": "automatic",
        "severity": "error",
        "generalization": "Проверяются официально-деловые обращения к пользователю.",
        "good_examples": ["Здравствуйте."],
        "bad_examples": ["Уважаемый пользователь!"],
    },
]

_PRIORITY_BY_SEVERITY = {"error": 90, "warning": 60, "suggestion": 40}


def _add_authority_metadata(rule: dict[str, Any]) -> None:
    """Дополняет правило метаданными для поиска, не меняя исторический формат реестра."""
    categories = list(dict.fromkeys(
        value for value in (rule.get("group"), str(rule.get("section", "")).split(" / ")[0])
        if value
    ))
    rule.setdefault("categories", categories)
    rule.setdefault("tasks", ["proofreading"])
    rule.setdefault("scope", "all")
    rule.setdefault("priority", _PRIORITY_BY_SEVERITY.get(rule.get("severity"), 50))
    rule.setdefault("mandatory", False)
    rule.setdefault(
        "machine_verifiable",
        rule.get("automation") == "automatic" and rule.get("engine") != "manual",
    )
    rule.setdefault("relationships", {})


for _rule in RULES:
    _add_authority_metadata(_rule)

SPELLING_LAYER_RULE = {
    "id": "LanguageTool.ru",
    "section": "Орфография",
    "group": "Орфография",
    "name": "LanguageTool",
    "rule": "Фильтруемый слой орфографии, грамматики и пунктуации. Это не источник правил Style Guide.",
    "engine": "languagetool",
    "automation": "automatic",
    "severity": "error",
    "generalization": "LanguageTool применяется отдельно от стайлгайда и фильтруется технической лексикой.",
    "good_examples": ["Ботнет использует терабитный канал."],
    "bad_examples": ["В тексте есть очепятка."],
}

_add_authority_metadata(SPELLING_LAYER_RULE)

REGISTRY: list[dict[str, Any]] = [*RULES, SPELLING_LAYER_RULE]


def get_registry(include_spelling: bool = True) -> list[dict[str, Any]]:
    rules = REGISTRY if include_spelling else RULES
    return [dict(rule, source_document=STYLE_GUIDE_SOURCE) for rule in rules]


def get_rule(rule_id: str) -> dict[str, Any] | None:
    return next((rule for rule in REGISTRY if rule["id"] == rule_id), None)


def enabled_vale_rule_ids() -> set[str]:
    return {
        rule["id"]
        for rule in RULES
        if rule["engine"] == "vale" and rule["automation"] != "manual"
    }


def style_guide_rule_ids() -> set[str]:
    return {rule["id"] for rule in RULES if rule["automation"] != "manual"}
